# Generated by Django 5.1.6 on 2025-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_address_locality_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
    ]
