# Generated by Django 5.1.6 on 2025-02-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='razorepay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
