# Generated by Django 5.1.6 on 2025-02-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shiping Amount'),
        ),
    ]
