# Generated by Django 5.1.6 on 2025-02-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_shiping_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shiping_charges',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=10, verbose_name='Shiping Amount'),
        ),
    ]
