# Generated by Django 5.1.6 on 2025-02-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_shiping_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shiping_charges',
        ),
    ]
