# Generated by Django 5.1.6 on 2025-02-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_order_shiping_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shiping_charge',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=10),
        ),
    ]
