# Generated by Django 5.1.6 on 2025-02-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_cart_shiping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shiping_charge',
        ),
    ]
