# Generated by Django 5.1.6 on 2025-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_address_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user_phone_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
