# Generated by Django 5.1.6 on 2025-04-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_tracking_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
